// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppleDailyMetric struct {
	MetricName string
	MeasuredAt time.Time
	Source     string
	Qty        float64
	Units      string
}

type AppleImport struct {
	ID             int64
	SourceFilename string
	SourceSha256   string
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	WorkoutsAdded  *int32
	MetricsAdded   *int32
	ImportedAt     time.Time
}

type AppleWorkout struct {
	ID               string
	Name             string
	Source           *string
	IsIndoor         *bool
	Location         *string
	StartedAt        time.Time
	EndedAt          time.Time
	DurationSeconds  float64
	DistanceKm       *float64
	ActiveEnergyKj   *float64
	AvgHrBpm         *float64
	MaxHrBpm         *float64
	MinHrBpm         *float64
	ElevationUpM     *float64
	AvgSpeed         *float64
	SpeedUnits       *string
	StepCadence      *float64
	HumidityPct      *float64
	Temperature      *float64
	TemperatureUnits *string
	Intensity        *float64
	Payload          []byte
	CreatedAt        time.Time
}

type AppleWorkoutHeartRate struct {
	WorkoutID  string
	MeasuredAt time.Time
	MinBpm     *float64
	MaxBpm     *float64
	AvgBpm     *float64
}

type AppleWorkoutRoute struct {
	ID                 int64
	WorkoutID          string
	RecordedAt         time.Time
	Latitude           float64
	Longitude          float64
	AltitudeM          *float64
	Speed              *float64
	HorizontalAccuracy *float64
	CourseAccuracy     *float64
}
