// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkoutHeartRate = `-- name: DeleteWorkoutHeartRate :exec
DELETE FROM apple_workout_heart_rate WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutHeartRate(ctx context.Context, workoutID string) error {
	_, err := q.db.Exec(ctx, deleteWorkoutHeartRate, workoutID)
	return err
}

const deleteWorkoutRoute = `-- name: DeleteWorkoutRoute :exec
DELETE FROM apple_workout_route WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutRoute(ctx context.Context, workoutID string) error {
	_, err := q.db.Exec(ctx, deleteWorkoutRoute, workoutID)
	return err
}

const getImportBySha256 = `-- name: GetImportBySha256 :one
SELECT id, source_filename, source_sha256, range_start, range_end,
       workouts_added, metrics_added, imported_at
  FROM apple_imports
 WHERE source_sha256 = $1
`

func (q *Queries) GetImportBySha256(ctx context.Context, sourceSha256 string) (AppleImport, error) {
	row := q.db.QueryRow(ctx, getImportBySha256, sourceSha256)
	var i AppleImport
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.RangeStart,
		&i.RangeEnd,
		&i.WorkoutsAdded,
		&i.MetricsAdded,
		&i.ImportedAt,
	)
	return i, err
}

const insertImport = `-- name: InsertImport :one
INSERT INTO apple_imports (
    source_filename, source_sha256, range_start, range_end,
    workouts_added, metrics_added
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source_filename, source_sha256, range_start, range_end,
          workouts_added, metrics_added, imported_at
`

type InsertImportParams struct {
	SourceFilename string
	SourceSha256   string
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	WorkoutsAdded  *int32
	MetricsAdded   *int32
}

func (q *Queries) InsertImport(ctx context.Context, arg InsertImportParams) (AppleImport, error) {
	row := q.db.QueryRow(ctx, insertImport,
		arg.SourceFilename,
		arg.SourceSha256,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkoutsAdded,
		arg.MetricsAdded,
	)
	var i AppleImport
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.RangeStart,
		&i.RangeEnd,
		&i.WorkoutsAdded,
		&i.MetricsAdded,
		&i.ImportedAt,
	)
	return i, err
}

const listDailyMetrics = `-- name: ListDailyMetrics :many
SELECT metric_name, measured_at, source, qty, units
  FROM apple_daily_metrics
 WHERE measured_at >= $1
   AND measured_at <  $2
   AND (COALESCE(cardinality($3::text[]),   0) = 0 OR metric_name = ANY($3::text[]))
   AND (COALESCE(cardinality($4::text[]), 0) = 0 OR source      = ANY($4::text[]))
 ORDER BY metric_name, measured_at
`

type ListDailyMetricsParams struct {
	FromAt  time.Time
	ToAt    time.Time
	Names   []string
	Sources []string
}

func (q *Queries) ListDailyMetrics(ctx context.Context, arg ListDailyMetricsParams) ([]AppleDailyMetric, error) {
	rows, err := q.db.Query(ctx, listDailyMetrics,
		arg.FromAt,
		arg.ToAt,
		arg.Names,
		arg.Sources,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleDailyMetric{}
	for rows.Next() {
		var i AppleDailyMetric
		if err := rows.Scan(
			&i.MetricName,
			&i.MeasuredAt,
			&i.Source,
			&i.Qty,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricNames = `-- name: ListMetricNames :many
SELECT DISTINCT metric_name FROM apple_daily_metrics ORDER BY metric_name
`

func (q *Queries) ListMetricNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listMetricNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var metric_name string
		if err := rows.Scan(&metric_name); err != nil {
			return nil, err
		}
		items = append(items, metric_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutHeartRate = `-- name: ListWorkoutHeartRate :many
SELECT workout_id, measured_at, min_bpm, max_bpm, avg_bpm
  FROM apple_workout_heart_rate
 WHERE workout_id = ANY($1::uuid[])
 ORDER BY workout_id, measured_at
`

func (q *Queries) ListWorkoutHeartRate(ctx context.Context, workoutIds []string) ([]AppleWorkoutHeartRate, error) {
	rows, err := q.db.Query(ctx, listWorkoutHeartRate, workoutIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleWorkoutHeartRate{}
	for rows.Next() {
		var i AppleWorkoutHeartRate
		if err := rows.Scan(
			&i.WorkoutID,
			&i.MeasuredAt,
			&i.MinBpm,
			&i.MaxBpm,
			&i.AvgBpm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutNames = `-- name: ListWorkoutNames :many
SELECT DISTINCT name FROM apple_workouts ORDER BY name
`

func (q *Queries) ListWorkoutNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listWorkoutNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutRoute = `-- name: ListWorkoutRoute :many
SELECT id, workout_id, recorded_at, latitude, longitude,
       altitude_m, speed, horizontal_accuracy, course_accuracy
  FROM apple_workout_route
 WHERE workout_id = ANY($1::uuid[])
 ORDER BY workout_id, recorded_at
`

func (q *Queries) ListWorkoutRoute(ctx context.Context, workoutIds []string) ([]AppleWorkoutRoute, error) {
	rows, err := q.db.Query(ctx, listWorkoutRoute, workoutIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleWorkoutRoute{}
	for rows.Next() {
		var i AppleWorkoutRoute
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.RecordedAt,
			&i.Latitude,
			&i.Longitude,
			&i.AltitudeM,
			&i.Speed,
			&i.HorizontalAccuracy,
			&i.CourseAccuracy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many

SELECT id, name, source, is_indoor, location,
       started_at, ended_at, duration_seconds,
       distance_km, active_energy_kj,
       avg_hr_bpm, max_hr_bpm, min_hr_bpm,
       elevation_up_m, avg_speed, speed_units,
       step_cadence, humidity_pct,
       temperature, temperature_units,
       intensity, payload, created_at
  FROM apple_workouts
 WHERE started_at >= $1
   AND started_at <  $2
   AND (COALESCE(cardinality($3::text[]), 0) = 0 OR name = ANY($3::text[]))
 ORDER BY started_at DESC
 LIMIT $4
`

type ListWorkoutsParams struct {
	FromAt time.Time
	ToAt   time.Time
	Names  []string
	Lim    int32
}

// NULL or empty arrays disable the corresponding filter.
// cardinality(NULL) returns NULL in PG, so we wrap with COALESCE.
func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]AppleWorkout, error) {
	rows, err := q.db.Query(ctx, listWorkouts,
		arg.FromAt,
		arg.ToAt,
		arg.Names,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleWorkout{}
	for rows.Next() {
		var i AppleWorkout
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.IsIndoor,
			&i.Location,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.DistanceKm,
			&i.ActiveEnergyKj,
			&i.AvgHrBpm,
			&i.MaxHrBpm,
			&i.MinHrBpm,
			&i.ElevationUpM,
			&i.AvgSpeed,
			&i.SpeedUnits,
			&i.StepCadence,
			&i.HumidityPct,
			&i.Temperature,
			&i.TemperatureUnits,
			&i.Intensity,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyMetric = `-- name: UpsertDailyMetric :exec
INSERT INTO apple_daily_metrics (metric_name, measured_at, source, qty, units)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (metric_name, measured_at, source) DO UPDATE SET
    qty   = EXCLUDED.qty,
    units = EXCLUDED.units
`

type UpsertDailyMetricParams struct {
	MetricName string
	MeasuredAt time.Time
	Source     string
	Qty        float64
	Units      string
}

func (q *Queries) UpsertDailyMetric(ctx context.Context, arg UpsertDailyMetricParams) error {
	_, err := q.db.Exec(ctx, upsertDailyMetric,
		arg.MetricName,
		arg.MeasuredAt,
		arg.Source,
		arg.Qty,
		arg.Units,
	)
	return err
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO apple_workouts (
    id, name, source, is_indoor, location,
    started_at, ended_at, duration_seconds,
    distance_km, active_energy_kj,
    avg_hr_bpm, max_hr_bpm, min_hr_bpm,
    elevation_up_m, avg_speed, speed_units,
    step_cadence, humidity_pct,
    temperature, temperature_units,
    intensity, payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21, $22
)
ON CONFLICT (id) DO UPDATE SET
    name              = EXCLUDED.name,
    source            = EXCLUDED.source,
    is_indoor         = EXCLUDED.is_indoor,
    location          = EXCLUDED.location,
    started_at        = EXCLUDED.started_at,
    ended_at          = EXCLUDED.ended_at,
    duration_seconds  = EXCLUDED.duration_seconds,
    distance_km       = EXCLUDED.distance_km,
    active_energy_kj  = EXCLUDED.active_energy_kj,
    avg_hr_bpm        = EXCLUDED.avg_hr_bpm,
    max_hr_bpm        = EXCLUDED.max_hr_bpm,
    min_hr_bpm        = EXCLUDED.min_hr_bpm,
    elevation_up_m    = EXCLUDED.elevation_up_m,
    avg_speed         = EXCLUDED.avg_speed,
    speed_units       = EXCLUDED.speed_units,
    step_cadence      = EXCLUDED.step_cadence,
    humidity_pct      = EXCLUDED.humidity_pct,
    temperature       = EXCLUDED.temperature,
    temperature_units = EXCLUDED.temperature_units,
    intensity         = EXCLUDED.intensity,
    payload           = EXCLUDED.payload
`

type UpsertWorkoutParams struct {
	ID               string
	Name             string
	Source           *string
	IsIndoor         *bool
	Location         *string
	StartedAt        time.Time
	EndedAt          time.Time
	DurationSeconds  float64
	DistanceKm       *float64
	ActiveEnergyKj   *float64
	AvgHrBpm         *float64
	MaxHrBpm         *float64
	MinHrBpm         *float64
	ElevationUpM     *float64
	AvgSpeed         *float64
	SpeedUnits       *string
	StepCadence      *float64
	HumidityPct      *float64
	Temperature      *float64
	TemperatureUnits *string
	Intensity        *float64
	Payload          []byte
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.IsIndoor,
		arg.Location,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.DistanceKm,
		arg.ActiveEnergyKj,
		arg.AvgHrBpm,
		arg.MaxHrBpm,
		arg.MinHrBpm,
		arg.ElevationUpM,
		arg.AvgSpeed,
		arg.SpeedUnits,
		arg.StepCadence,
		arg.HumidityPct,
		arg.Temperature,
		arg.TemperatureUnits,
		arg.Intensity,
		arg.Payload,
	)
	return err
}
