// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStravaActivities = `-- name: CountStravaActivities :one
SELECT COUNT(*) FROM strava_activities WHERE strava_athlete_id = $1
`

func (q *Queries) CountStravaActivities(ctx context.Context, stravaAthleteID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStravaActivities, stravaAthleteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStravaTokens = `-- name: DeleteStravaTokens :exec
DELETE FROM strava_tokens WHERE strava_athlete_id = $1
`

func (q *Queries) DeleteStravaTokens(ctx context.Context, stravaAthleteID int64) error {
	_, err := q.db.Exec(ctx, deleteStravaTokens, stravaAthleteID)
	return err
}

const deleteWorkoutHeartRate = `-- name: DeleteWorkoutHeartRate :exec
DELETE FROM apple_workout_heart_rate WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutHeartRate(ctx context.Context, workoutID string) error {
	_, err := q.db.Exec(ctx, deleteWorkoutHeartRate, workoutID)
	return err
}

const deleteWorkoutRoute = `-- name: DeleteWorkoutRoute :exec
DELETE FROM apple_workout_route WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutRoute(ctx context.Context, workoutID string) error {
	_, err := q.db.Exec(ctx, deleteWorkoutRoute, workoutID)
	return err
}

const getImportBySha256 = `-- name: GetImportBySha256 :one
SELECT id, source_filename, source_sha256, range_start, range_end,
       workouts_added, metrics_added, imported_at
  FROM apple_imports
 WHERE source_sha256 = $1
`

func (q *Queries) GetImportBySha256(ctx context.Context, sourceSha256 string) (AppleImport, error) {
	row := q.db.QueryRow(ctx, getImportBySha256, sourceSha256)
	var i AppleImport
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.RangeStart,
		&i.RangeEnd,
		&i.WorkoutsAdded,
		&i.MetricsAdded,
		&i.ImportedAt,
	)
	return i, err
}

const getRateLimit = `-- name: GetRateLimit :one
SELECT short_limit, short_usage, daily_limit, daily_usage, updated_at
  FROM strava_rate_limit
 WHERE id = 1
`

type GetRateLimitRow struct {
	ShortLimit int32
	ShortUsage int32
	DailyLimit int32
	DailyUsage int32
	UpdatedAt  time.Time
}

func (q *Queries) GetRateLimit(ctx context.Context) (GetRateLimitRow, error) {
	row := q.db.QueryRow(ctx, getRateLimit)
	var i GetRateLimitRow
	err := row.Scan(
		&i.ShortLimit,
		&i.ShortUsage,
		&i.DailyLimit,
		&i.DailyUsage,
		&i.UpdatedAt,
	)
	return i, err
}

const getStravaTokens = `-- name: GetStravaTokens :one
SELECT strava_athlete_id, access_token, refresh_token, expires_at, updated_at
  FROM strava_tokens
 WHERE strava_athlete_id = $1
`

func (q *Queries) GetStravaTokens(ctx context.Context, stravaAthleteID int64) (StravaToken, error) {
	row := q.db.QueryRow(ctx, getStravaTokens, stravaAthleteID)
	var i StravaToken
	err := row.Scan(
		&i.StravaAthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncState = `-- name: GetSyncState :one
SELECT strava_athlete_id, last_synced_at, last_activity_at
  FROM strava_sync_state
 WHERE strava_athlete_id = $1
`

func (q *Queries) GetSyncState(ctx context.Context, stravaAthleteID int64) (StravaSyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState, stravaAthleteID)
	var i StravaSyncState
	err := row.Scan(&i.StravaAthleteID, &i.LastSyncedAt, &i.LastActivityAt)
	return i, err
}

const insertImport = `-- name: InsertImport :one
INSERT INTO apple_imports (
    source_filename, source_sha256, range_start, range_end,
    workouts_added, metrics_added
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source_filename, source_sha256, range_start, range_end,
          workouts_added, metrics_added, imported_at
`

type InsertImportParams struct {
	SourceFilename string
	SourceSha256   string
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	WorkoutsAdded  *int32
	MetricsAdded   *int32
}

func (q *Queries) InsertImport(ctx context.Context, arg InsertImportParams) (AppleImport, error) {
	row := q.db.QueryRow(ctx, insertImport,
		arg.SourceFilename,
		arg.SourceSha256,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkoutsAdded,
		arg.MetricsAdded,
	)
	var i AppleImport
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.RangeStart,
		&i.RangeEnd,
		&i.WorkoutsAdded,
		&i.MetricsAdded,
		&i.ImportedAt,
	)
	return i, err
}

const linkTelegramChat = `-- name: LinkTelegramChat :exec
INSERT INTO telegram_strava_links (telegram_chat_id, strava_athlete_id)
VALUES ($1, $2)
ON CONFLICT (telegram_chat_id) DO UPDATE SET
    strava_athlete_id = EXCLUDED.strava_athlete_id,
    linked_at         = now()
`

type LinkTelegramChatParams struct {
	TelegramChatID  int64
	StravaAthleteID int64
}

func (q *Queries) LinkTelegramChat(ctx context.Context, arg LinkTelegramChatParams) error {
	_, err := q.db.Exec(ctx, linkTelegramChat, arg.TelegramChatID, arg.StravaAthleteID)
	return err
}

const listDailyMetrics = `-- name: ListDailyMetrics :many
SELECT metric_name, measured_at, source, qty, units
  FROM apple_daily_metrics
 WHERE measured_at >= $1
   AND measured_at <  $2
   AND (COALESCE(cardinality($3::text[]),   0) = 0 OR metric_name = ANY($3::text[]))
   AND (COALESCE(cardinality($4::text[]), 0) = 0 OR source      = ANY($4::text[]))
 ORDER BY metric_name, measured_at
`

type ListDailyMetricsParams struct {
	FromAt  time.Time
	ToAt    time.Time
	Names   []string
	Sources []string
}

func (q *Queries) ListDailyMetrics(ctx context.Context, arg ListDailyMetricsParams) ([]AppleDailyMetric, error) {
	rows, err := q.db.Query(ctx, listDailyMetrics,
		arg.FromAt,
		arg.ToAt,
		arg.Names,
		arg.Sources,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleDailyMetric{}
	for rows.Next() {
		var i AppleDailyMetric
		if err := rows.Scan(
			&i.MetricName,
			&i.MeasuredAt,
			&i.Source,
			&i.Qty,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricNames = `-- name: ListMetricNames :many
SELECT DISTINCT metric_name FROM apple_daily_metrics ORDER BY metric_name
`

func (q *Queries) ListMetricNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listMetricNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var metric_name string
		if err := rows.Scan(&metric_name); err != nil {
			return nil, err
		}
		items = append(items, metric_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentStravaActivities = `-- name: ListRecentStravaActivities :many
SELECT strava_activity_id, strava_athlete_id, name, sport_type, workout_type,
       start_at, start_at_local, timezone,
       distance_m, moving_time_s, elapsed_time_s, elevation_gain_m,
       average_speed_mps, max_speed_mps, average_heartrate, max_heartrate,
       average_watts, average_cadence, suffer_score,
       trainer, commute, payload, fetched_at
  FROM strava_activities
 WHERE strava_athlete_id = $1
   AND start_at >= $2
 ORDER BY start_at DESC
 LIMIT $3
`

type ListRecentStravaActivitiesParams struct {
	AthleteID int64
	Since     time.Time
	Lim       int32
}

func (q *Queries) ListRecentStravaActivities(ctx context.Context, arg ListRecentStravaActivitiesParams) ([]StravaActivity, error) {
	rows, err := q.db.Query(ctx, listRecentStravaActivities, arg.AthleteID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StravaActivity{}
	for rows.Next() {
		var i StravaActivity
		if err := rows.Scan(
			&i.StravaActivityID,
			&i.StravaAthleteID,
			&i.Name,
			&i.SportType,
			&i.WorkoutType,
			&i.StartAt,
			&i.StartAtLocal,
			&i.Timezone,
			&i.DistanceM,
			&i.MovingTimeS,
			&i.ElapsedTimeS,
			&i.ElevationGainM,
			&i.AverageSpeedMps,
			&i.MaxSpeedMps,
			&i.AverageHeartrate,
			&i.MaxHeartrate,
			&i.AverageWatts,
			&i.AverageCadence,
			&i.SufferScore,
			&i.Trainer,
			&i.Commute,
			&i.Payload,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutHeartRate = `-- name: ListWorkoutHeartRate :many
SELECT workout_id, measured_at, min_bpm, max_bpm, avg_bpm
  FROM apple_workout_heart_rate
 WHERE workout_id = ANY($1::uuid[])
 ORDER BY workout_id, measured_at
`

func (q *Queries) ListWorkoutHeartRate(ctx context.Context, workoutIds []string) ([]AppleWorkoutHeartRate, error) {
	rows, err := q.db.Query(ctx, listWorkoutHeartRate, workoutIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleWorkoutHeartRate{}
	for rows.Next() {
		var i AppleWorkoutHeartRate
		if err := rows.Scan(
			&i.WorkoutID,
			&i.MeasuredAt,
			&i.MinBpm,
			&i.MaxBpm,
			&i.AvgBpm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutNames = `-- name: ListWorkoutNames :many
SELECT DISTINCT name FROM apple_workouts ORDER BY name
`

func (q *Queries) ListWorkoutNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listWorkoutNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutRoute = `-- name: ListWorkoutRoute :many
SELECT id, workout_id, recorded_at, latitude, longitude,
       altitude_m, speed, horizontal_accuracy, course_accuracy
  FROM apple_workout_route
 WHERE workout_id = ANY($1::uuid[])
 ORDER BY workout_id, recorded_at
`

func (q *Queries) ListWorkoutRoute(ctx context.Context, workoutIds []string) ([]AppleWorkoutRoute, error) {
	rows, err := q.db.Query(ctx, listWorkoutRoute, workoutIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleWorkoutRoute{}
	for rows.Next() {
		var i AppleWorkoutRoute
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.RecordedAt,
			&i.Latitude,
			&i.Longitude,
			&i.AltitudeM,
			&i.Speed,
			&i.HorizontalAccuracy,
			&i.CourseAccuracy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many

SELECT id, name, source, is_indoor, location,
       started_at, ended_at, duration_seconds,
       distance_km, active_energy_kj,
       avg_hr_bpm, max_hr_bpm, min_hr_bpm,
       elevation_up_m, avg_speed, speed_units,
       step_cadence, humidity_pct,
       temperature, temperature_units,
       intensity, payload, created_at
  FROM apple_workouts
 WHERE started_at >= $1
   AND started_at <  $2
   AND (COALESCE(cardinality($3::text[]), 0) = 0 OR name = ANY($3::text[]))
 ORDER BY started_at DESC
 LIMIT $4
`

type ListWorkoutsParams struct {
	FromAt time.Time
	ToAt   time.Time
	Names  []string
	Lim    int32
}

// NULL or empty arrays disable the corresponding filter.
// cardinality(NULL) returns NULL in PG, so we wrap with COALESCE.
func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]AppleWorkout, error) {
	rows, err := q.db.Query(ctx, listWorkouts,
		arg.FromAt,
		arg.ToAt,
		arg.Names,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleWorkout{}
	for rows.Next() {
		var i AppleWorkout
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.IsIndoor,
			&i.Location,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.DistanceKm,
			&i.ActiveEnergyKj,
			&i.AvgHrBpm,
			&i.MaxHrBpm,
			&i.MinHrBpm,
			&i.ElevationUpM,
			&i.AvgSpeed,
			&i.SpeedUnits,
			&i.StepCadence,
			&i.HumidityPct,
			&i.Temperature,
			&i.TemperatureUnits,
			&i.Intensity,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAthleteByChat = `-- name: ResolveAthleteByChat :one
SELECT strava_athlete_id FROM telegram_strava_links WHERE telegram_chat_id = $1
`

func (q *Queries) ResolveAthleteByChat(ctx context.Context, telegramChatID int64) (int64, error) {
	row := q.db.QueryRow(ctx, resolveAthleteByChat, telegramChatID)
	var strava_athlete_id int64
	err := row.Scan(&strava_athlete_id)
	return strava_athlete_id, err
}

const unlinkAthleteFromAllChats = `-- name: UnlinkAthleteFromAllChats :exec
DELETE FROM telegram_strava_links WHERE strava_athlete_id = $1
`

func (q *Queries) UnlinkAthleteFromAllChats(ctx context.Context, stravaAthleteID int64) error {
	_, err := q.db.Exec(ctx, unlinkAthleteFromAllChats, stravaAthleteID)
	return err
}

const unlinkTelegramChat = `-- name: UnlinkTelegramChat :exec
DELETE FROM telegram_strava_links WHERE telegram_chat_id = $1
`

func (q *Queries) UnlinkTelegramChat(ctx context.Context, telegramChatID int64) error {
	_, err := q.db.Exec(ctx, unlinkTelegramChat, telegramChatID)
	return err
}

const updateRateLimit = `-- name: UpdateRateLimit :exec
UPDATE strava_rate_limit
   SET short_limit  = $1,
       short_usage  = $2,
       daily_limit  = $3,
       daily_usage  = $4,
       updated_at   = now()
 WHERE id = 1
`

type UpdateRateLimitParams struct {
	ShortLimit int32
	ShortUsage int32
	DailyLimit int32
	DailyUsage int32
}

func (q *Queries) UpdateRateLimit(ctx context.Context, arg UpdateRateLimitParams) error {
	_, err := q.db.Exec(ctx, updateRateLimit,
		arg.ShortLimit,
		arg.ShortUsage,
		arg.DailyLimit,
		arg.DailyUsage,
	)
	return err
}

const upsertDailyMetric = `-- name: UpsertDailyMetric :exec
INSERT INTO apple_daily_metrics (metric_name, measured_at, source, qty, units)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (metric_name, measured_at, source) DO UPDATE SET
    qty   = EXCLUDED.qty,
    units = EXCLUDED.units
`

type UpsertDailyMetricParams struct {
	MetricName string
	MeasuredAt time.Time
	Source     string
	Qty        float64
	Units      string
}

func (q *Queries) UpsertDailyMetric(ctx context.Context, arg UpsertDailyMetricParams) error {
	_, err := q.db.Exec(ctx, upsertDailyMetric,
		arg.MetricName,
		arg.MeasuredAt,
		arg.Source,
		arg.Qty,
		arg.Units,
	)
	return err
}

const upsertStravaActivity = `-- name: UpsertStravaActivity :exec
INSERT INTO strava_activities (
    strava_activity_id, strava_athlete_id, name, sport_type, workout_type,
    start_at, start_at_local, timezone,
    distance_m, moving_time_s, elapsed_time_s, elevation_gain_m,
    average_speed_mps, max_speed_mps, average_heartrate, max_heartrate,
    average_watts, average_cadence, suffer_score,
    trainer, commute, payload, fetched_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, now()
)
ON CONFLICT (strava_activity_id) DO UPDATE SET
    name              = EXCLUDED.name,
    sport_type        = EXCLUDED.sport_type,
    workout_type      = EXCLUDED.workout_type,
    start_at          = EXCLUDED.start_at,
    start_at_local    = EXCLUDED.start_at_local,
    timezone          = EXCLUDED.timezone,
    distance_m        = EXCLUDED.distance_m,
    moving_time_s     = EXCLUDED.moving_time_s,
    elapsed_time_s    = EXCLUDED.elapsed_time_s,
    elevation_gain_m  = EXCLUDED.elevation_gain_m,
    average_speed_mps = EXCLUDED.average_speed_mps,
    max_speed_mps     = EXCLUDED.max_speed_mps,
    average_heartrate = EXCLUDED.average_heartrate,
    max_heartrate     = EXCLUDED.max_heartrate,
    average_watts     = EXCLUDED.average_watts,
    average_cadence   = EXCLUDED.average_cadence,
    suffer_score      = EXCLUDED.suffer_score,
    trainer           = EXCLUDED.trainer,
    commute           = EXCLUDED.commute,
    payload           = EXCLUDED.payload,
    fetched_at        = now()
`

type UpsertStravaActivityParams struct {
	StravaActivityID int64
	StravaAthleteID  int64
	Name             string
	SportType        string
	WorkoutType      *int32
	StartAt          time.Time
	StartAtLocal     pgtype.Timestamptz
	Timezone         *string
	DistanceM        *float64
	MovingTimeS      *int32
	ElapsedTimeS     *int32
	ElevationGainM   *float64
	AverageSpeedMps  *float64
	MaxSpeedMps      *float64
	AverageHeartrate *float64
	MaxHeartrate     *float64
	AverageWatts     *float64
	AverageCadence   *float64
	SufferScore      *int32
	Trainer          *bool
	Commute          *bool
	Payload          []byte
}

func (q *Queries) UpsertStravaActivity(ctx context.Context, arg UpsertStravaActivityParams) error {
	_, err := q.db.Exec(ctx, upsertStravaActivity,
		arg.StravaActivityID,
		arg.StravaAthleteID,
		arg.Name,
		arg.SportType,
		arg.WorkoutType,
		arg.StartAt,
		arg.StartAtLocal,
		arg.Timezone,
		arg.DistanceM,
		arg.MovingTimeS,
		arg.ElapsedTimeS,
		arg.ElevationGainM,
		arg.AverageSpeedMps,
		arg.MaxSpeedMps,
		arg.AverageHeartrate,
		arg.MaxHeartrate,
		arg.AverageWatts,
		arg.AverageCadence,
		arg.SufferScore,
		arg.Trainer,
		arg.Commute,
		arg.Payload,
	)
	return err
}

const upsertStravaAthlete = `-- name: UpsertStravaAthlete :exec

INSERT INTO strava_athletes (
    strava_athlete_id, username, firstname, lastname,
    city, country, sex, weight_kg, ftp_watts, profile_url, fetched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (strava_athlete_id) DO UPDATE SET
    username    = EXCLUDED.username,
    firstname   = EXCLUDED.firstname,
    lastname    = EXCLUDED.lastname,
    city        = EXCLUDED.city,
    country     = EXCLUDED.country,
    sex         = EXCLUDED.sex,
    weight_kg   = EXCLUDED.weight_kg,
    ftp_watts   = EXCLUDED.ftp_watts,
    profile_url = EXCLUDED.profile_url,
    fetched_at  = now()
`

type UpsertStravaAthleteParams struct {
	StravaAthleteID int64
	Username        *string
	Firstname       *string
	Lastname        *string
	City            *string
	Country         *string
	Sex             *string
	WeightKg        *float64
	FtpWatts        *int32
	ProfileUrl      *string
}

// ============================================================
// Strava
// ============================================================
func (q *Queries) UpsertStravaAthlete(ctx context.Context, arg UpsertStravaAthleteParams) error {
	_, err := q.db.Exec(ctx, upsertStravaAthlete,
		arg.StravaAthleteID,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.City,
		arg.Country,
		arg.Sex,
		arg.WeightKg,
		arg.FtpWatts,
		arg.ProfileUrl,
	)
	return err
}

const upsertStravaTokens = `-- name: UpsertStravaTokens :exec
INSERT INTO strava_tokens (strava_athlete_id, access_token, refresh_token, expires_at, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (strava_athlete_id) DO UPDATE SET
    access_token  = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expires_at    = EXCLUDED.expires_at,
    updated_at    = now()
`

type UpsertStravaTokensParams struct {
	StravaAthleteID int64
	AccessToken     string
	RefreshToken    string
	ExpiresAt       time.Time
}

func (q *Queries) UpsertStravaTokens(ctx context.Context, arg UpsertStravaTokensParams) error {
	_, err := q.db.Exec(ctx, upsertStravaTokens,
		arg.StravaAthleteID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}

const upsertSyncState = `-- name: UpsertSyncState :exec
INSERT INTO strava_sync_state (strava_athlete_id, last_synced_at, last_activity_at)
VALUES ($1, now(), $2)
ON CONFLICT (strava_athlete_id) DO UPDATE SET
    last_synced_at   = now(),
    last_activity_at = EXCLUDED.last_activity_at
`

type UpsertSyncStateParams struct {
	StravaAthleteID int64
	LastActivityAt  pgtype.Timestamptz
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertSyncState, arg.StravaAthleteID, arg.LastActivityAt)
	return err
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO apple_workouts (
    id, name, source, is_indoor, location,
    started_at, ended_at, duration_seconds,
    distance_km, active_energy_kj,
    avg_hr_bpm, max_hr_bpm, min_hr_bpm,
    elevation_up_m, avg_speed, speed_units,
    step_cadence, humidity_pct,
    temperature, temperature_units,
    intensity, payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21, $22
)
ON CONFLICT (id) DO UPDATE SET
    name              = EXCLUDED.name,
    source            = EXCLUDED.source,
    is_indoor         = EXCLUDED.is_indoor,
    location          = EXCLUDED.location,
    started_at        = EXCLUDED.started_at,
    ended_at          = EXCLUDED.ended_at,
    duration_seconds  = EXCLUDED.duration_seconds,
    distance_km       = EXCLUDED.distance_km,
    active_energy_kj  = EXCLUDED.active_energy_kj,
    avg_hr_bpm        = EXCLUDED.avg_hr_bpm,
    max_hr_bpm        = EXCLUDED.max_hr_bpm,
    min_hr_bpm        = EXCLUDED.min_hr_bpm,
    elevation_up_m    = EXCLUDED.elevation_up_m,
    avg_speed         = EXCLUDED.avg_speed,
    speed_units       = EXCLUDED.speed_units,
    step_cadence      = EXCLUDED.step_cadence,
    humidity_pct      = EXCLUDED.humidity_pct,
    temperature       = EXCLUDED.temperature,
    temperature_units = EXCLUDED.temperature_units,
    intensity         = EXCLUDED.intensity,
    payload           = EXCLUDED.payload
`

type UpsertWorkoutParams struct {
	ID               string
	Name             string
	Source           *string
	IsIndoor         *bool
	Location         *string
	StartedAt        time.Time
	EndedAt          time.Time
	DurationSeconds  float64
	DistanceKm       *float64
	ActiveEnergyKj   *float64
	AvgHrBpm         *float64
	MaxHrBpm         *float64
	MinHrBpm         *float64
	ElevationUpM     *float64
	AvgSpeed         *float64
	SpeedUnits       *string
	StepCadence      *float64
	HumidityPct      *float64
	Temperature      *float64
	TemperatureUnits *string
	Intensity        *float64
	Payload          []byte
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.IsIndoor,
		arg.Location,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.DistanceKm,
		arg.ActiveEnergyKj,
		arg.AvgHrBpm,
		arg.MaxHrBpm,
		arg.MinHrBpm,
		arg.ElevationUpM,
		arg.AvgSpeed,
		arg.SpeedUnits,
		arg.StepCadence,
		arg.HumidityPct,
		arg.Temperature,
		arg.TemperatureUnits,
		arg.Intensity,
		arg.Payload,
	)
	return err
}
