// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkoutHeartRate = `-- name: DeleteWorkoutHeartRate :exec
DELETE FROM apple_workout_heart_rate WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutHeartRate(ctx context.Context, workoutID string) error {
	_, err := q.db.Exec(ctx, deleteWorkoutHeartRate, workoutID)
	return err
}

const deleteWorkoutRoute = `-- name: DeleteWorkoutRoute :exec
DELETE FROM apple_workout_route WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutRoute(ctx context.Context, workoutID string) error {
	_, err := q.db.Exec(ctx, deleteWorkoutRoute, workoutID)
	return err
}

const getImportBySha256 = `-- name: GetImportBySha256 :one
SELECT id, source_filename, source_sha256, range_start, range_end,
       workouts_added, metrics_added, imported_at
  FROM apple_imports
 WHERE source_sha256 = $1
`

func (q *Queries) GetImportBySha256(ctx context.Context, sourceSha256 string) (AppleImport, error) {
	row := q.db.QueryRow(ctx, getImportBySha256, sourceSha256)
	var i AppleImport
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.RangeStart,
		&i.RangeEnd,
		&i.WorkoutsAdded,
		&i.MetricsAdded,
		&i.ImportedAt,
	)
	return i, err
}

const insertImport = `-- name: InsertImport :one
INSERT INTO apple_imports (
    source_filename, source_sha256, range_start, range_end,
    workouts_added, metrics_added
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source_filename, source_sha256, range_start, range_end,
          workouts_added, metrics_added, imported_at
`

type InsertImportParams struct {
	SourceFilename string
	SourceSha256   string
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	WorkoutsAdded  *int32
	MetricsAdded   *int32
}

func (q *Queries) InsertImport(ctx context.Context, arg InsertImportParams) (AppleImport, error) {
	row := q.db.QueryRow(ctx, insertImport,
		arg.SourceFilename,
		arg.SourceSha256,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkoutsAdded,
		arg.MetricsAdded,
	)
	var i AppleImport
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.RangeStart,
		&i.RangeEnd,
		&i.WorkoutsAdded,
		&i.MetricsAdded,
		&i.ImportedAt,
	)
	return i, err
}

const upsertDailyMetric = `-- name: UpsertDailyMetric :exec
INSERT INTO apple_daily_metrics (metric_name, measured_at, source, qty, units)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (metric_name, measured_at, source) DO UPDATE SET
    qty   = EXCLUDED.qty,
    units = EXCLUDED.units
`

type UpsertDailyMetricParams struct {
	MetricName string
	MeasuredAt time.Time
	Source     string
	Qty        float64
	Units      string
}

func (q *Queries) UpsertDailyMetric(ctx context.Context, arg UpsertDailyMetricParams) error {
	_, err := q.db.Exec(ctx, upsertDailyMetric,
		arg.MetricName,
		arg.MeasuredAt,
		arg.Source,
		arg.Qty,
		arg.Units,
	)
	return err
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO apple_workouts (
    id, name, source, is_indoor, location,
    started_at, ended_at, duration_seconds,
    distance_km, active_energy_kj,
    avg_hr_bpm, max_hr_bpm, min_hr_bpm,
    elevation_up_m, avg_speed, speed_units,
    step_cadence, humidity_pct,
    temperature, temperature_units,
    intensity, payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21, $22
)
ON CONFLICT (id) DO UPDATE SET
    name              = EXCLUDED.name,
    source            = EXCLUDED.source,
    is_indoor         = EXCLUDED.is_indoor,
    location          = EXCLUDED.location,
    started_at        = EXCLUDED.started_at,
    ended_at          = EXCLUDED.ended_at,
    duration_seconds  = EXCLUDED.duration_seconds,
    distance_km       = EXCLUDED.distance_km,
    active_energy_kj  = EXCLUDED.active_energy_kj,
    avg_hr_bpm        = EXCLUDED.avg_hr_bpm,
    max_hr_bpm        = EXCLUDED.max_hr_bpm,
    min_hr_bpm        = EXCLUDED.min_hr_bpm,
    elevation_up_m    = EXCLUDED.elevation_up_m,
    avg_speed         = EXCLUDED.avg_speed,
    speed_units       = EXCLUDED.speed_units,
    step_cadence      = EXCLUDED.step_cadence,
    humidity_pct      = EXCLUDED.humidity_pct,
    temperature       = EXCLUDED.temperature,
    temperature_units = EXCLUDED.temperature_units,
    intensity         = EXCLUDED.intensity,
    payload           = EXCLUDED.payload
`

type UpsertWorkoutParams struct {
	ID               string
	Name             string
	Source           *string
	IsIndoor         *bool
	Location         *string
	StartedAt        time.Time
	EndedAt          time.Time
	DurationSeconds  float64
	DistanceKm       *float64
	ActiveEnergyKj   *float64
	AvgHrBpm         *float64
	MaxHrBpm         *float64
	MinHrBpm         *float64
	ElevationUpM     *float64
	AvgSpeed         *float64
	SpeedUnits       *string
	StepCadence      *float64
	HumidityPct      *float64
	Temperature      *float64
	TemperatureUnits *string
	Intensity        *float64
	Payload          []byte
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.IsIndoor,
		arg.Location,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.DistanceKm,
		arg.ActiveEnergyKj,
		arg.AvgHrBpm,
		arg.MaxHrBpm,
		arg.MinHrBpm,
		arg.ElevationUpM,
		arg.AvgSpeed,
		arg.SpeedUnits,
		arg.StepCadence,
		arg.HumidityPct,
		arg.Temperature,
		arg.TemperatureUnits,
		arg.Intensity,
		arg.Payload,
	)
	return err
}
